/**
 * Generate public/config.js from the environment at build time.
 *
 * The board needs the API token in the browser, but the token must not live in
 * git. So it is written into a gitignored file during the Vercel build, from the
 * API_TOKEN environment variable set in the Vercel project.
 *
 * Locally the Node server serves /config.js dynamically from the environment
 * instead, so there is nothing to keep in sync during development.
 *
 * Note the token is readable by anyone who loads the board — that is inherent to
 * putting a credential in a browser, and is documented as a known limitation.
 * This step exists to keep the secret out of the repository, not to hide it from
 * someone who already has the page.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const OUTPUT = fileURLToPath(new URL("../public/config.js", import.meta.url));

export function renderConfig(env: NodeJS.ProcessEnv = process.env): string {
  const options: Record<string, unknown> = {};
  if (env.API_TOKEN) options.token = env.API_TOKEN;
  if (env.BOARD_API_ENDPOINT) options.endpoint = env.BOARD_API_ENDPOINT;

  return (
    "/* Generated by scripts/write-config.ts — do not edit, do not commit. */\n" +
    "window.BOARD_API_OPTIONS = Object.assign(window.BOARD_API_OPTIONS || {}, " +
    JSON.stringify(options) +
    ");\n"
  );
}

async function main(): Promise<void> {
  await mkdir(fileURLToPath(new URL("../public", import.meta.url)), { recursive: true });
  await writeFile(OUTPUT, renderConfig(), "utf8");
  console.log(
    "[config] wrote public/config.js " +
      (process.env.API_TOKEN ? "(with an API token)" : "(no API token — the API is open)"),
  );
}

// Only run when invoked directly, so tests can import renderConfig.
if (process.argv[1] && fileURLToPath(new URL(import.meta.url)) === process.argv[1]) {
  main().catch((error) => {
    console.error("[config] failed:", error);
    process.exitCode = 1;
  });
}
